library(ggplot2)
library(dplyr)
library(GGally)
library(gridExtra)

rm(list = ls())

getwd()
setwd("../Naver/")
data = read.csv("data.csv")

str(data)

summary(data)
sum(is.na(data))

data$diagnosis = factor(data$diagnosis, levels = c("B", "M"), labels = c("Benign", "Malignant"))

round(prop.table(table(data$diagnosis))*100,1)
ggplot(data, aes(diagnosis)) + geom_bar() + ggtitle('Diagnosis of breast tissue')
ggpairs(data[23:32])

colnames(data)

pr1 = ggplot(data, aes(radius_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pt1 = ggplot(data, aes(texture_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pp1 = ggplot(data, aes(perimeter_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pa1 = ggplot(data, aes(area_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psm1 = ggplot(data, aes(smoothness_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pca1 = ggplot(data, aes(compactness_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcc1 = ggplot(data, aes(concavity_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcp1 = ggplot(data, aes(concave.points_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psy1 = ggplot(data, aes(symmetry_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pfd1 = ggplot(data, aes(fractal_dimension_mean)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)

pr2 = ggplot(data, aes(radius_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pt2 = ggplot(data, aes(texture_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pp2 = ggplot(data, aes(perimeter_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pa2 = ggplot(data, aes(area_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psm2 = ggplot(data, aes(smoothness_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pca2 = ggplot(data, aes(compactness_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcc2 = ggplot(data, aes(concavity_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcp2 = ggplot(data, aes(concave.points_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psy2 = ggplot(data, aes(symmetry_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pfd2 = ggplot(data, aes(fractal_dimension_se)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)

pr3 = ggplot(data, aes(radius_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pt3 = ggplot(data, aes(texture_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pp3 = ggplot(data, aes(perimeter_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pa3 = ggplot(data, aes(area_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psm3 = ggplot(data, aes(smoothness_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pca3 = ggplot(data, aes(compactness_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcc3 = ggplot(data, aes(concavity_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pcp3 = ggplot(data, aes(concave.points_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
psy3 = ggplot(data, aes(symmetry_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)
pfd3 = ggplot(data, aes(fractal_dimension_worst)) + geom_density(aes(fill = diagnosis), alpha = 0.7, lwd = 1)

grid.arrange(pr1,pr2,pr3, nrow=3)
grid.arrange(pt1,pt2,pt3, nrow=3)
grid.arrange(pp1,pp2,pp3, nrow=3)
grid.arrange(pa1,pa2,pa3, nrow=3)
grid.arrange(psm1,psm2,psm3, nrow=3)
grid.arrange(pca1,pca2,pca3, nrow=3)
grid.arrange(pcc1,pcc2,pcc3, nrow=3)
grid.arrange(pcp1,pcp2,pcp3, nrow=3)
grid.arrange(psy1,psy2,psy3, nrow=3)
grid.arrange(pfd1,pfd2,pfd3, nrow=3)
